export const ActionTypes = {
    SET_CONTENT_STATE : "SET_CONTENT_STATE",

    FETCH_ITEMS : "FETCH_ITEMS",
    SET_ITEM_STATE : "SET_ITEM_STATE",

    SET_VARIANT_STATE : "SET_VARIANT_STATE",

    FETCH_CATEGORIES_DROPDOWN : "FETCH_CATEGORIES_DROPDOWN",
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    SET_CATEGORY_STATE: "SET_CATEGORY_STATE",

    FETCH_TAXES_DROPDOWN : "FETCH_TAXES_DROPDOWN",
    FETCH_TAXES: "FETCH_TAXES",

    FETCH_CURRENCIES_DROPDOWN : "FETCH_CURRENCIES_DROPDOWN",
    FETCH_CURRENCIES: "FETCH_CURRENCIES",
    SET_CURRENCY_STATE: "SET_CURRENCY_STATE",

    FETCH_TAXES_DROPDOWN : "FETCH_TAXES_DROPDOWN",
    FETCH_TAXES: "FETCH_TAXES",
    SET_TAX_STATE: "SET_TAX_STATE",

    FETCH_CONTACTS_DROPDOWN : "FETCH_CONTACTS_DROPDOWN",
    FETCH_CONTACTS: "FETCH_CONTACTS",
    SET_CONTACT_STATE: "SET_CONTACT_STATE",

    FETCH_VENDORS_DROPDOWN : "FETCH_VENDORS_DROPDOWN",
    FETCH_VENDORS: "FETCH_VENDORS",
    SET_VENDOR_STATE: "SET_VENDOR_STATE",

    FETCH_ACCOUNTS_DROPDOWN : "FETCH_ACCOUNTS_DROPDOWN",
    FETCH_ACCOUNTS: "FETCH_ACCOUNTS",
    SET_ACCOUNT_STATE: "SET_ACCOUNT_STATE",

    FETCH_REVENUES_DROPDOWN : "FETCH_REVENUES_DROPDOWN",
    FETCH_REVENUES: "FETCH_REVENUES",
    SET_REVENUE_STATE: "SET_REVENUE_STATE",

    FETCH_DEFAULT_SETTING : "FETCH_DEFAULT_SETTING",
    FETCH_DEFAULT_CURRENCY : "FETCH_DEFAULT_CURRENCY",

    FETCH_EXPENSES_DROPDOWN : "FETCH_EXPENSES_DROPDOWN",
    FETCH_EXPENSES: "FETCH_EXPENSES",
    SET_EXPENSE_STATE: "SET_EXPENSE_STATE",

    FETCH_USERS: "FETCH_USERS",
    SET_USER_STATE: "SET_USER_STATE",

    FETCH_TRANSFERS: "FETCH_TRANSFERS",
    SET_TRANSFER_STATE: "SET_TRANSFER_STATE",

    FETCH_TRANSACTIONS: "FETCH_TRANSACTIONS",
    SET_TRANSACTION_STATE: "SET_TRANSACTION_STATE",

    FETCH_INVOICES: "FETCH_INVOICES",
    SET_INVOICE_STATE: "SET_INVOICE_STATE",

    FETCH_BILLS: "FETCH_BILLS",
    SET_BILL_STATE: "SET_BILL_STATE",
}